version: '4.3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: navarro
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'